name: AA Demo V2 CI/CD
on:
  push:
    branches:
      - 'aa-demo-v2'
  pull_request:
    branches:
      - 'aa-demo-v2'
  workflow_dispatch:

env:
  CI: false

jobs:
  deploy:
    name: build && push image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get short SHA and short Run ID
        id: vars
        run: |
            echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            echo "run_id_short=${GITHUB_RUN_ID:0:3}" >> $GITHUB_OUTPUT

      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            github/data/general/docker/esatya username | DOCKERHUB_USERNAME ;
            github/data/general/docker/esatya password | DOCKERHUB_TOKEN ;

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build && push events-app
        id: build-push-events-app
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.triggers
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: |
            esatya/rahat-project-triggers:aa-demo-v2
            esatya/rahat-project-triggers:aa-demo-v2-${{ steps.vars.outputs.sha_short }}-${{ steps.vars.outputs.run_id_short }}

    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
      run_id_short: ${{ steps.vars.outputs.run_id_short }}

  