name: Dev CI/CD
on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"

env:
  CI: false

jobs:
  deploy:
    name: build && push image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
              github/data/general/docker/esatya username | DOCKERHUB_USERNAME ;
              github/data/general/docker/esatya password | DOCKERHUB_TOKEN ;

      - name: Debug Secrets
        env:
            DOCKERHUB_USERNAME: ${{ env.DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN: ${{ env.DOCKERHUB_TOKEN }}
        run: |
            echo "DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}"
            echo "DOCKERHUB_TOKEN=${DOCKERHUB_TOKEN}"


      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
            
    #   - name: Set up Docker Buildx
    #     uses: docker/setup-buildx-action@v3

     # Events-App Image
    #   - name: build && push events-app
    #     id: build-push-events-app
    #     uses: docker/build-push-action@v5
    #     with:
    #       context: .
    #       file: Dockerfile
    #       push: ${{ github.event_name == 'push' && 'true' || 'false' }}
    #       tags: esatya/rahat-project-triggers:dev
