name: AA Test Load

on:
  push:
    branches:
      - test-load
  workflow_dispatch:

jobs:
  call-core:
    uses: rahataid/rahat-project-triggers/.github/workflows/AA-Core-CICD.yaml@test-load
    with:
      image_name: rahat-project-triggers
      dockerfile_path: apps/triggers/Dockerfile.triggers
      tag_prefix: test-load
    secrets: inherit
