name: Test Coveralls
on: ["push", "pull_request"]
jobs:

  test:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20.10.0

      - name: install dependencies and build apps
        run: |
          npm install -g pnpm@8.14.1 only-allow
          pnpm install

      - name: npm install, make test-coverage
        run: |
          pnpm test-coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}